tf2: Add tf2_geometry_msgs dependency
ros/geometry2 pull request #170
Opened 2016-04-09 09:03 UTC by kartikmohta

`tf2/include/tf2/impl/utils.h` includes `tf2_geometry_msgs/tf2_geometry_msgs.h` but the dependency is missing

2016-04-12 19:27 UTC, tfoote commented
@ros-pull-request-builder retest this please

2016-04-12 19:33 UTC, tfoote commented
Thanks for catching that. It is a problem. However adding this dependency creates a circular dependency since `tf2_geometry_msgs` depends on `tf2` thus we should move the implementation into `tf2_geometry_msgs` since it cannot be used without that package anyway.

2016-04-12 20:15 UTC, kartikmohta commented
Yeah agreed, seems like some restructuring is required so I'll let you guys do it the right way :)

2017-07-24 17:20 UTC, tfoote requested changes
As mentioned in the comment this causes an issue with circular depedencies. I'm going to mark this as changes requested for tracking purposes.

2018-03-22 00:20 UTC, tfoote commented
I'm going to close this as there's now a ticket tracking it in #275 with a discussion of a better way to resolve this.

2018-03-22 00:20 UTC, closed without merging