add RPY parameter handling
ros/geometry2 pull request #232
Opened 2017-05-08 15:45 UTC by dvanthienen

2017-05-08 19:20 UTC, tfoote requested changes
Thanks this looks good overall. 

I had a few quick comments about units and decreasing the complexity.

It would be great to add at least a basic unit test of the code path too.

2017-05-08 19:20 UTC, tfoote commented on tf2_ros/doc/index.rst
> +    | tf_frame_to_be_published_parameter_name/transform/rotation/R: deg(0.0)
This should be radians not degrees.

2017-05-08 19:20 UTC, tfoote commented on tf2_ros/src/static_transform_broadcaster_program.cpp
> +      msg.transform.translation.x = (double) tf_data["transform"]["translation"]["x"];
The translation block is duplicated in the two conditionals. Please move it below the else where it can be reused for both quaternion and rpy interface.

2017-05-08 19:20 UTC, tfoote commented on tf2_ros/src/static_transform_broadcaster_program.cpp
> +      msg.header.stamp = ros::Time::now();
The header logic can also be consolidated.

2017-05-11 09:00 UTC, dvanthienen commented on tf2_ros/doc/index.rst
> +    | tf_frame_to_be_published_parameter_name/transform/rotation/R: deg(0.0)
It is in radians, but making use of the more readable degree notation and the degree to radian conversion option: https://github.com/ros/ros_comm/blob/247459207e20c1da109fc306e58b84d15c4107bd/tools/rosparam/src/rosparam/__init__.py#L116

2017-05-11 09:27 UTC, dvanthienen commented
@tfoote PTAL

2017-05-12 21:04 UTC, tfoote commented on tf2_ros/doc/index.rst
> +    | tf_frame_to_be_published_parameter_name/transform/rotation/R: deg(0.0)
Ahh, I wasn't aware of that extension. That's great.

2017-05-12 21:04 UTC, tfoote commented
This looks good now. It just needs at least a basic test.

2024-02-02 14:16 UTC, ahcorde commented
This PR is targeting a [EOL distribution melodic](http://wiki.ros.org/Distributions), closing this PR, feel free to reopen this against a maintained branch

2024-02-02 14:16 UTC, closed without merging