Make the subscriber queue size mutable.
ros/geometry2 pull request #249
Opened 2017-07-07 11:55 UTC by kojiterada

Make the subscriber queue size mutable.

2017-07-07 20:54 UTC, tfoote requested changes
Thanks this looks like a good extension. I had a few comments. 

And when updating the doc block please also comment about side effecting on other subscribers: http://docs.ros.org/kinetic/api/rospy/html/rospy.topics.Subscriber-class.html wrt to the queue size.

2017-07-07 20:54 UTC, tfoote commented on tf2_ros/src/tf2_ros/transform_listener.py
>          self.tf_static_sub = rospy.Subscriber("/tf_static", TFMessage, self.static_callback)
The queue_size should also propogate here.

2017-07-07 20:54 UTC, tfoote commented on tf2_ros/src/tf2_ros/transform_listener.py
>              :param buffer: The buffer to propagate changes to when tf info updates.
Please update the doc block too.

2017-07-10 00:10 UTC, kojiterada commented on tf2_ros/src/tf2_ros/transform_listener.py
>              :param buffer: The buffer to propagate changes to when tf info updates.
I updated doc block.

2017-07-10 00:10 UTC, kojiterada commented on tf2_ros/src/tf2_ros/transform_listener.py
>          self.tf_static_sub = rospy.Subscriber("/tf_static", TFMessage, self.static_callback)
I also change there.

2017-07-10 03:50 UTC, tfoote approved these changes
Thanks for the iteration. And exposing the extra options looks good too.

2017-07-10 03:51 UTC, merged