add PoseWithCovariance to tf2_geometry_msgs.h
ros/geometry2 pull request #300
Opened 2018-06-19 22:56 UTC by fabolhak

2018-06-20 00:28 UTC, tfoote requested changes
Adding support for PoseWithCovariance is fine. But it cannot be converted into a Transform and back so that shouldn't be defined, otherwise it will compile and run, but give invalid data.

2018-06-20 00:28 UTC, tfoote commented on tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h
> +void fromMsg(const geometry_msgs::PoseWithCovariance& msg, tf2::Transform& out)
This is not isomorphic and thus should not be defined using this structure.

2018-06-20 00:28 UTC, tfoote commented on tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h
> +{
This is not isomorphic and thus should not be defined using this structure.

2018-06-20 07:09 UTC, fabolhak commented
Thank you for the feedback! I wasn't so sure about those two anyway. So I just removed them. Would that be ok?

2018-06-20 18:38 UTC, tfoote commented
> Thank you for the feedback! I wasn't so sure about those two anyway. So I just removed them. Would that be ok?

That's fine thanks.

> I'm just a little bit confused why these conversions work for Pose and PoseWithCovariancesStamped, though.

Sorry can you explain a little bit about what's confusing?

2018-07-02 20:10 UTC, fabolhak commented
I'm not really familiar with the term isomorphic. Are the conversion to and from `tf2::Transform` not isomorphic because we lose the covariance information?

But this also happens with the `PoseWithCovarianceStamped` conversions [here](https://github.com/fabolhak/geometry2/blob/27109065e4cc6a3c887b916dd0c778728e4ec56e/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L623) and [here](https://github.com/fabolhak/geometry2/blob/27109065e4cc6a3c887b916dd0c778728e4ec56e/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h#L638) :confused: .

2018-07-03 06:22 UTC, tfoote commented
Yes, it shouldn't loose data.

Those are both bugs that need to be resolved.

2019-07-10 15:13 UTC, artivis commented
Looks like this PR could be merged nop ?
Removing the two `PoseWithCovarianceStamped`-related erroneous conversion should happen in another PR.

2024-02-02 14:16 UTC, ahcorde commented
This PR is targeting a [EOL distribution melodic](http://wiki.ros.org/Distributions), closing this PR, feel free to reopen this against a maintained branch

2024-02-02 14:16 UTC, closed without merging