fixed nan interpolation issue
ros/geometry2 pull request #311
Opened 2018-07-11 09:25 UTC by bluenote10

fixes #310

2018-07-11 21:18 UTC, tfoote requested changes
This is working around the symptom by testing it in the same way. It would be much better to not do double comparisons of large values. 

If you instead changed the ratio to diff the times into a Duration, that would all be integer math. And then just call `Duration::toSec` on the results the problem would be avoided completely. 

And you also aren't doing floating point comparisions or extra conversions to floating point.

2018-07-12 08:17 UTC, bluenote10 commented
How would you do that exactly? `Duration` does not have division and using `Duration::toSec` on the numerator and denominator separately probably doesn't fully solve the problem, because the denominator again can become zero. I could change the check to be `(two.stamp_ - one.stamp_).toSec() == 0` accordingly?

2018-07-12 20:35 UTC, tfoote commented
A floating point representation won't have a problem representing a single nanosecond and will not "become" zero. It only looses precision with large values so if you do the differencing in fixed point math. It's safe to do the division using the floating point representation of the deltas (which are small).

2018-07-12 20:39 UTC, tfoote commented on tf2/src/cache.cpp
> +  if ((two.stamp_ - one.stamp_).toSec() == 0)
This change is not necessary and causes noteable extra computation.

2018-07-13 17:08 UTC, tfoote commented
Thanks for the fixup, with the revert there's now a whole bunch of unrelated whitespace changes. Generally they're good, but having the unrelated changes in the diffs will make tracking across branches much harder. Please keep the diff minimal to just the code changes.

2018-07-16 07:43 UTC, bluenote10 commented
Closing in favor of #313

2018-07-16 07:43 UTC, closed without merging