Follow #337: use actionlib API in BufferClient::processGoal()
ros/geometry2 pull request #360
Opened 2019-02-18 17:28 UTC by MichaelGrupp

Follows the changes to the Python API from #337 to simplify the action client logic.

2019-02-18 17:31 UTC, MichaelGrupp commented
The second commit probably needs to be changed, depending on how you want to handle parameter deprecation.

2019-02-20 08:19 UTC, tfoote requested changes
Thanks this is good to do as well. You're right about the 2nd commit. It's good to clean up, but stability is more valuable for now than saving the memory of a single double value.

2019-02-20 08:19 UTC, tfoote commented on tf2_ros/include/tf2_ros/buffer_client.h
> -      double check_frequency_;
If we leave this here with a note that it's unused then this change can be ABI compatible and can then be made available in active distros without need for a discussion.

2019-02-20 08:19 UTC, tfoote commented on tf2_ros/src/buffer_client.cpp
> -    check_frequency_(check_frequency),
If we keep the member for compatibility we should still initialize it to avoid warnings.

2019-02-20 09:03 UTC, MichaelGrupp commented
Thanks for the quick review. I changed the 2nd commit to be ABI compliant.

2019-02-20 09:04 UTC, tfoote approved these changes

2019-02-20 09:20 UTC, tfoote commented
Thank you for the patch and iterating on it!

2019-02-20 09:20 UTC, merged